PROGRAM NAVIER_STOKES

    USE CONSTANTS
    USE FUNCTIONS

    IMPLICIT NONE

    DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: RE, CF, BL
    DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:, :) :: XNODE, YNODE, XCELL, YCELL, &
        UCELL, VCELL, PCELL

    ALLOCATE(RE(NI), CF(NI), BL(NI), XNODE(0: NI, 0: NJ), YNODE(0: NI, 0: NJ), &
        XCELL(0: NI, 0: NJ), YCELL(0: NI, 0: NJ), UCELL(0: NI, 0: NJ), &
        VCELL(0: NI, 0: NJ), PCELL(0: NI, 0: NJ))

    CALL CREATE_MESH(XNODE, YNODE, XCELL, YCELL)
    CALL NAVIER_STOKES_SOLVER(UCELL, VCELL, PCELL)
    CALL NUMERICAL_FRICTION(UCELL, CF)
    CALL BLASIUS_FRICTION(XNODE, RE, BL)
    CALL CREATE_FILES(XNODE, YNODE, UCELL, VCELL, PCELL, RE, CF, BL)

    DEALLOCATE(RE, CF, BL, XNODE, YNODE, XCELL, YCELL, UCELL, VCELL, PCELL)

END PROGRAM NAVIER_STOKES
