PROGRAM PRANDTL

    USE CONSTANTS
    USE FUNCTIONS

    IMPLICIT NONE

    DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: RE, CF, BL
    DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:, :) :: X, Y, U, V, P

    ALLOCATE(RE(NI), CF(NI), BL(NI), X(NI, NJ), Y(NI, NJ), &
        U(NI, NJ), V(NI, NJ), P(NI, NJ))

    CALL CREATE_MESH(X, Y)
    CALL SIMUNI_PRANDTL_SOLVER(U, V, P)
    CALL NUMERICAL_FRICTION(U, CF)
    CALL BLASIUS_FRICTION(X, RE, BL)
    CALL CREATE_FILES(X, Y, U, V, P, RE, CF, BL)

    DEALLOCATE(RE, CF, BL, X, Y, U, V, P)

END PROGRAM PRANDTL
